import {
  LayoutDashboard,
  BookOpen,
  FileText,
  FileSpreadsheet,
  ClipboardCheck,
  BarChart3,
  Eye,
  HelpCircle,
  User,
  Bell,
  Award,
  Users,
  Upload,
  Download,
  Settings,
  Lock,
  MessageSquare,
  Shield,
  Activity,
  Clock,
  CheckCircle,
  XCircle,
  AlertTriangle,
} from "lucide-react";

export const LecturerIcons = {
  Dashboard: LayoutDashboard,
  Courses: BookOpen,
  Questions: FileText,
  Exams: FileSpreadsheet,
  Submissions: ClipboardCheck,
  Reports: BarChart3,
  Monitoring: Eye,
  Support: HelpCircle,
  Profile: User,
  Notifications: Bell,
  Results: Award,
  Students: Users,
  Upload: Upload,
  Download: Download,
  Settings: Settings,
  Password: Lock,
  Announcements: MessageSquare,
  Integrity: Shield,
  Live: Activity,
  History: Clock,
  Approved: CheckCircle,
  Rejected: XCircle,
  Pending: AlertTriangle,
};

export default LecturerIcons;
